### PR TITLE
Add Zulu version 1.8.292

### PR DESCRIPTION
**Pull request by saschpe**

### CODE REVIEW

**Comment by saschpe** [comment]
I did this manually and verified all URLs as well. Is there a way to automate this?

**Comment by saschpe** [comment]
Ping

**Comment by saschpe** [comment]
Ping?

**Comment by willcohen** [comment]
https://github.com/shyiko/jabba/issues/833

**Comment by saschpe** [comment]
Looks like not much is gonna happen here.

**Pull request closed without merging**
