### PR TITLE
Added AdoptOpenJDK 1.11.0.8+10

### PR DESCRIPTION
**Pull request by MihaiBojin**

### CODE REVIEW

**Comment by MihaiBojin** [comment]
Hi @shyiko , can you please review my PR? I added Adopt 11.0.8 since it's available. Thanks!

**Comment by MihaiBojin** [comment]
Hi @shyiko, a friendly reminder to review this PR. Thanks!

**Comment by tony--** [comment]
+1

**Comment by willcohen** [comment]
Fixed with 0f64255!

**Pull request closed without merging**
