### PR TITLE
allow any alias

### PR DESCRIPTION
**Pull request by mikethebos**
@shyiko Is there a reason why this was not allowed by default?

### CODE REVIEW

**Comment by leonard84** [comment]
@shyiko are there any reasons to not merge this?

**Comment by michaelcusick** [comment]
@willcohen @shyiko bumping.

**Comment by Petersoj** [comment]
+1 Please merge this! It's quite convenient.

**Comment by willcohen** [comment]
Sorry for the delay. It’s been so long since a release — I know we owe a good look through all open PRs before cutting a new release.

**Pull request merged**
